[package]
name = "rust-ldw"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
syn = { workspace = true }
proc-macro2 = { workspace = true }
#quote2 = { workspace = true }
#minijinja = { workspace = true }
#serde = { workspace = true }
quote = "1.0.40"
