[package]
name = "transform"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
deluxe = "0.5.0"
proc-macro2 = { workspace = true }
quote2 = { workspace = true }
syn = { workspace = true }
